version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '11:32'
      timezone: "Asia/Jakarta"
    labels:
      - dependencies
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-major]
    commit-message:
      prefix: ci
      include: scope
