version: "3.8"
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 8.2
        NODE_VERSION: lts/*
      labels:
        devcontainer.metadata: |
          [{
            "features": {
              "git": "latest"
            }
          }]
    user: vscode
    volumes:
      - ..:/workspaces/basement-chat:cached
    working_dir: /workspaces/basement-chat
    container_name: devcontainer
    command: sleep infinity
