name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      APP_URL: '127.0.0.1:8001'
      APP_ENV: testing
      APP_DEBUG: true
      APP_KEY: 'base64:IDrlmrVwu65iBhbUpPq3fsv7kybcnfUFZmY1wk+mamE='
      DB_CONNECTION: sqlite
      BROADCAST_DRIVER: pusher
      BASEMENT_BROADCAST_DRIVER: pusher
      SESSION_DRIVER: cookie
      SANCTUM_STATEFUL_DOMAINS: '127.0.0.1:8001'
      PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
      PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
      PUSHER_APP_SECRET: ${{ secrets.PUSHER_APP_SECRET }}
      PUSHER_APP_CLUSTER: ${{ secrets.PUSHER_APP_CLUSTER }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.0]
        laravel: [9.*]
        stability: [prefer-stable]
        include:
          - laravel: 9.*
            testbench: 7.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: List installed dependencies
        run: composer show -D

      - name: Set up testing
        run: |
          ./vendor/orchestra/testbench-core/create-sqlite-db
          ./vendor/orchestra/testbench-dusk/create-sqlite-db
          ./vendor/bin/dusk-updater detect --auto-update

      - name: Execute tests
        run: composer test -- --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
